#!/usr/bin/env bash
# 10-worklog.sh — Cross-machine work-log capture (+ curator vault) setup.
# Dependencies: lib/common.sh, lib/config.sh, lib/dryrun.sh
#
# Sets up the capture-at-source work-log pipeline on this machine:
#   * writes ~/.config/worklog/config (read by the /worklog command)
#   * deploys the /worklog command (always) and /worklog-sync (curators only)
#   * clones the inbox if GitHub access is already present, else defers the
#     clone to first /worklog use (the private inbox is NOT a hard install dep)
#
# Roles: "capture" (default, fail-safe) sets up the inbox only; "curator"
# additionally clones the obsidian vault — so the vault never lands on a
# capture-only (work / shared) machine. Set role/source per machine in
# config.local.yaml.

# _worklog_expand <path> — resolve a $HOME-relative path; absolute paths pass through
_worklog_expand() {
    local p="$1"
    case "$p" in
        /*) printf '%s\n' "$p" ;;
        *) printf '%s\n' "${HOME}/${p}" ;;
    esac
}

# _worklog_write_config — render ~/.config/worklog/config (read by /worklog)
_worklog_write_config() {
    local src_label="$1" role="$2" inbox_repo="$3" inbox_path="$4" vault_repo="$5" vault_path="$6"
    local dir="${HOME}/.config/worklog"
    local dest="${dir}/config"
    local content
    content=$(
        printf '%s\n' "# Generated by env-setup 10-worklog — do not edit by hand."
        printf 'WORKLOG_SOURCE=%s\n' "$src_label"
        printf 'WORKLOG_ROLE=%s\n' "$role"
        printf 'WORKLOG_INBOX_REPO=%s\n' "$inbox_repo"
        printf 'WORKLOG_INBOX_PATH=%s\n' "$inbox_path"
        printf 'WORKLOG_VAULT_REPO=%s\n' "$vault_repo"
        printf 'WORKLOG_VAULT_PATH=%s\n' "$vault_path"
    )

    dry_run_mkdir "$dir"
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "[DRY-RUN] write ${dest}"
        return 0
    fi
    if [[ -f "$dest" && "$(cat "$dest")" == "$content" ]]; then
        log_info "[SKIP] ${dest} already up to date"
        return 0
    fi
    printf '%s\n' "$content" >"$dest"
    log_success "Wrote ${dest} (source=${src_label}, role=${role})"
}

# _worklog_has_access <owner/repo> — true if the active gh account can see it
_worklog_has_access() {
    command -v gh >/dev/null 2>&1 || return 1
    gh repo view "$1" >/dev/null 2>&1
}

# _worklog_clone <owner/repo> <dest> <label>
_worklog_clone() {
    local repo="$1" dest="$2" label="$3"

    if [[ -d "${dest}/.git" ]]; then
        log_info "[SKIP] ${label} already cloned at ${dest}"
        return 0
    fi
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_info "[DRY-RUN] clone ${repo} -> ${dest}"
        return 0
    fi

    if _worklog_has_access "$repo"; then
        dry_run_mkdir "$(dirname "$dest")"
        if gh repo clone "$repo" "$dest" >/dev/null 2>&1; then
            log_success "Cloned ${label} (${repo})"
        else
            log_warn "Clone of ${repo} failed — /worklog will retry on first use"
        fi
        return 0
    fi

    # No access yet — defer to lazy clone on first /worklog use (auth exists then).
    log_warn "No access to ${repo} yet (gh not authed, or this account isn't a collaborator)."
    log_info "  /worklog clones it lazily on first use once you are authenticated."
    log_info "  Non-owner machines: create a deploy key and have the inbox owner add it —"
    log_info "    ssh-keygen -t ed25519 -N '' -f \"\$HOME/.ssh/worklog_inbox\" -C \"worklog-\$(hostname -s)\""
    log_info "    then add \$HOME/.ssh/worklog_inbox.pub to ${repo} as a write deploy key (owner runs this)."
}

# _worklog_deploy_command <name>
_worklog_deploy_command() {
    local name="$1"
    local src="${ENV_SETUP_DIR}/configs/worklog/commands/${name}.md"
    local dest_dir="${HOME}/.claude/commands"
    dry_run_mkdir "$dest_dir"
    deploy_config "$src" "${dest_dir}/${name}.md" "/${name} command"
}

# Entry point — called by setup.sh
install_worklog() {
    if ! cfg_enabled "worklog.enabled"; then
        log_info "worklog disabled in config — skipping"
        return 0
    fi

    print_header "Worklog"

    local role src_label inbox_repo inbox_path vault_repo vault_path
    role="$(cfg_get "worklog.role")"
    [[ -z "$role" ]] && role="capture"
    src_label="$(cfg_get "worklog.source")"
    if [[ -z "$src_label" || "$src_label" == "auto" ]]; then
        src_label="$(hostname -s 2>/dev/null || hostname)"
    fi
    inbox_repo="$(cfg_get "worklog.inbox_repo")"
    inbox_path="$(_worklog_expand "$(cfg_get "worklog.inbox_path")")"
    vault_repo="$(cfg_get "worklog.vault_repo")"
    vault_path="$(_worklog_expand "$(cfg_get "worklog.vault_path")")"

    log_info "role=${role}  source=${src_label}"

    _worklog_write_config "$src_label" "$role" "$inbox_repo" "$inbox_path" "$vault_repo" "$vault_path"
    _worklog_deploy_command "worklog"
    _worklog_clone "$inbox_repo" "$inbox_path" "worklog-inbox"

    if [[ "$role" == "curator" ]]; then
        print_header "Worklog — curator (vault + sync)"
        _worklog_deploy_command "worklog-sync"
        _worklog_clone "$vault_repo" "$vault_path" "obsidian-notes vault"
        log_info "Vault auto-sync is obsidian-git (Obsidian-app side) — open the vault + enable the plugin once."
    fi
}

# Uninstall counterpart — called by uninstall.sh (reverse order)
uninstall_worklog() {
    print_header "Uninstall: Worklog"
    # Conservative: remove only the deployed commands + per-machine config.
    # NEVER touch the cloned inbox/vault or any logs (user data).

    # Deployed command files: byte-compare against the repo source so a copy the
    # user edited is preserved, not clobbered (matches 08-claude-code's teardown).
    local name
    for name in worklog worklog-sync; do
        remove_managed_file "${HOME}/.claude/commands/${name}.md" \
            "${ENV_SETUP_DIR}/configs/worklog/commands/${name}.md" "/${name} command"
    done

    # Generated runtime config has no repo source to verify against (so
    # remove_managed_file would refuse it) — remove it directly, dry-run aware.
    if [[ -f "${HOME}/.config/worklog/config" ]]; then
        dry_run_rm "${HOME}/.config/worklog/config"
    fi

    log_info "Left the inbox/vault clones and all logs untouched (user data)."
}
