#!/usr/bin/env pwsh
# 10-Worklog.ps1 — Cross-machine work-log capture (+ curator vault) setup.
# Windows-engine sibling of modules/10-worklog.sh. Sets up the capture-at-source
# work-log pipeline: writes the per-machine worklog config, deploys the /worklog
# command (and /worklog-sync for curators), and clones the inbox when GitHub
# access is present — otherwise the /worklog command clones it lazily on first
# use, so install never blocks on private-repo auth. Role "capture" (default,
# fail-safe) sets up the inbox only; "curator" also clones the obsidian vault.
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Import-Module "$PSScriptRoot/../lib/Common.psm1"
Import-Module "$PSScriptRoot/../lib/Config.psm1"
Import-Module "$PSScriptRoot/../lib/DryRun.psm1" -DisableNameChecking  # WinPS 5.1: 'Deploy' is an unapproved verb
Import-Module "$PSScriptRoot/../lib/Uninstall.psm1"  # Remove-ManagedFile (teardown)

$script:WorklogCmds = (Resolve-Path (Join-Path $PSScriptRoot '../configs/worklog/commands')).Path

function Resolve-WorklogPath {
    param([Parameter(Mandatory)][string]$Path)
    if ([System.IO.Path]::IsPathRooted($Path)) { return $Path }
    return (Join-Path $HOME $Path)
}

function Write-WorklogRuntimeConfig {
    param(
        [Parameter(Mandatory)][string]$SourceLabel,
        [Parameter(Mandatory)][string]$Role,
        [Parameter(Mandatory)][string]$InboxRepo,
        [Parameter(Mandatory)][string]$InboxPath,
        [Parameter(Mandatory)][string]$VaultRepo,
        [Parameter(Mandatory)][string]$VaultPath
    )
    $dir = Join-Path $HOME '.config/worklog'
    $dest = Join-Path $dir 'config'
    $content = (@(
            '# Generated by env-setup 10-Worklog — do not edit by hand.'
            "WORKLOG_SOURCE=$SourceLabel"
            "WORKLOG_ROLE=$Role"
            "WORKLOG_INBOX_REPO=$InboxRepo"
            "WORKLOG_INBOX_PATH=$InboxPath"
            "WORKLOG_VAULT_REPO=$VaultRepo"
            "WORKLOG_VAULT_PATH=$VaultPath"
        ) -join "`n")

    New-DirOrDryRun -Path $dir
    if (Test-DryRun) { Write-Info "[DRY-RUN] Would write $dest"; return }
    if (Test-Path -LiteralPath $dest) {
        $existing = [string](Get-Content -Raw -LiteralPath $dest)
        if ($existing.TrimEnd() -eq $content.TrimEnd()) { Write-Info "[SKIP] $dest already up to date"; return }
    }
    Set-Content -LiteralPath $dest -Value $content -Encoding utf8
    Write-Success "Wrote $dest (source=$SourceLabel, role=$Role)"
}

function Test-WorklogRepoAccess {
    param([Parameter(Mandatory)][string]$Repo)
    if (-not (Test-Command 'gh')) { return $false }
    gh repo view $Repo *> $null
    return ($LASTEXITCODE -eq 0)
}

function Sync-WorklogRepo {
    param(
        [Parameter(Mandatory)][string]$Repo,
        [Parameter(Mandatory)][string]$Dest,
        [Parameter(Mandatory)][string]$Label
    )
    if (Test-Path -LiteralPath (Join-Path $Dest '.git')) { Write-Info "[SKIP] $Label already cloned at $Dest"; return }
    if (Test-DryRun) { Write-Info "[DRY-RUN] Would clone $Repo -> $Dest"; return }

    if (Test-WorklogRepoAccess -Repo $Repo) {
        New-DirOrDryRun -Path (Split-Path $Dest -Parent)
        gh repo clone $Repo $Dest *> $null
        if ($LASTEXITCODE -eq 0) { Write-Success "Cloned $Label ($Repo)" }
        else { Write-Warn "Clone of $Repo failed — /worklog will retry on first use" }
        return
    }

    Write-Warn "No access to $Repo yet (gh not authed, or this account isn't a collaborator)."
    Write-Info '  /worklog clones it lazily on first use once you are authenticated.'
    Write-Info '  Non-owner machines: create a deploy key and have the inbox owner add it as a write deploy key.'
}

function Install-WorklogCommand {
    param([Parameter(Mandatory)][string]$Name)
    $src = Join-Path $script:WorklogCmds "$Name.md"
    $destDir = Join-Path $HOME '.claude/commands'
    New-DirOrDryRun -Path $destDir
    Deploy-Config -Source $src -Destination (Join-Path $destDir "$Name.md") -Label "/$Name command"
}

function Install-Worklog {
    if (-not (Test-CfgEnabled 'worklog.enabled')) { Write-Info 'worklog disabled in config — skipping'; return }
    Write-Header 'Worklog'

    $role = Get-CfgValue -Path 'worklog.role'
    if (-not $role) { $role = 'capture' }
    $source = Get-CfgValue -Path 'worklog.source'
    if (-not $source -or $source -eq 'auto') { $source = [System.Net.Dns]::GetHostName() }
    $inboxRepo = Get-CfgValue -Path 'worklog.inbox_repo'
    $inboxPath = Resolve-WorklogPath (Get-CfgValue -Path 'worklog.inbox_path')
    $vaultRepo = Get-CfgValue -Path 'worklog.vault_repo'
    $vaultPath = Resolve-WorklogPath (Get-CfgValue -Path 'worklog.vault_path')

    Write-Info "role=$role  source=$source"

    Write-WorklogRuntimeConfig -SourceLabel $source -Role $role `
        -InboxRepo $inboxRepo -InboxPath $inboxPath -VaultRepo $vaultRepo -VaultPath $vaultPath
    Install-WorklogCommand -Name 'worklog'
    Sync-WorklogRepo -Repo $inboxRepo -Dest $inboxPath -Label 'worklog-inbox'

    if ($role -eq 'curator') {
        Write-Header 'Worklog — curator (vault + sync)'
        Install-WorklogCommand -Name 'worklog-sync'
        Sync-WorklogRepo -Repo $vaultRepo -Dest $vaultPath -Label 'obsidian-notes vault'
        Write-Info 'Vault auto-sync is obsidian-git (Obsidian-app side) — open the vault + enable the plugin once.'
    }
}

function Uninstall-Worklog {
    Write-Header 'Uninstall: Worklog'
    # Conservative: remove only the deployed commands + per-machine config.
    # NEVER touch the cloned inbox/vault or any logs (user data).

    # Deployed command files: byte-compare against the repo source so a copy the
    # user edited is preserved, not clobbered (matches 08-ClaudeCode's teardown).
    foreach ($name in 'worklog', 'worklog-sync') {
        Remove-ManagedFile -Dest (Join-Path $HOME ".claude/commands/$name.md") `
            -RepoSrc (Join-Path $script:WorklogCmds "$name.md") -Label "/$name command"
    }

    # Generated runtime config has no repo source to verify against (so
    # Remove-ManagedFile would refuse it) — remove it directly, dry-run aware.
    $cfg = Join-Path $HOME '.config/worklog/config'
    if (Test-Path -LiteralPath $cfg) { Remove-OrDryRun -Path $cfg }

    Write-Info 'Left the inbox/vault clones and all logs untouched (user data).'
}
